apiVersion: v1
kind: Namespace
metadata:
  name: cc-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clothing-classifier-deployment
  namespace: cc-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clothing-classifier
  template:
    metadata:
      labels:
        app: clothing-classifier
    spec:
      containers:
        - name: clothing-classifier
          image: clothing-classification-model:1
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: clothing-classification-service
  namespace: cc-ns
spec:
  type: NodePort
  selector:
    app: clothing-classifier
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clothing-classification-hpa
  namespace: cc-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clothing-classifier-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
